drop table member if exists cascade;
create table member (
                        member_id varchar(10),
                        login_id varchar(10) not null,
                        name varchar(10) not null,
                        password varchar(10) not null,
                        primary key (member_id)
);

drop table if exists post CASCADE;
create table post
(
    id bigint generated by default as identity,
    title varchar(10),
    content varchar(256),
    login_id varchar(10),
    primary key (id)
);