name: Deploy to GCP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 최신 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설치 (Java 17 사용 시)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 빌드 수행 (Gradle Wrapper 사용 시)
      - name: Build application
        run: |
          cd Book_ManageSys/base/manage/
          chmod +x ./gradlew
          ./gradlew clean bootJar

      # 4. 원격 서버에 SSH로 접속하여 코드 Pull & Gradle 빌드 수행
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/project/Full/Book_ManageSys/base/manage
            git pull origin main
            chmod +x ./gradlew
            ./gradlew clean bootJar
            cd build/libs
            pkill -f "java -jar manage-0.0.1-SNAPSHOT.jar" || true
            setsid nohup java -jar manage-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &

